services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cache
    ports:
      - "5435:5432"
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    restart: always