### Create user
### Create just one user for test purpose
POST http://localhost:8080/users
Content-Type: application/json
X-TenantId: tenant_1

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get all user
GET http://localhost:8080/users
X-TenantId: tenant_1

### Get user by ID
### Must be an error
# {
#  "status": 500,
#  "error": "Internal Server Error",
#  "path": "/users/2"
# }
### as we have only one user for tenant_1
GET http://localhost:8080/users/2
X-TenantId: tenant_1

### Update user
PUT http://localhost:8080/users/1
Content-Type: application/json
X-TenantId: tenant_1

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}

### Delete user by ID
DELETE http://localhost:8080/users/1
X-TenantId: tenant_1

### Get current tenant
GET http://localhost:8080/tenant
X-TenantId: tenant_1

###  Subscribe tenant
PUT http://localhost:8080/callback/tenant/1
X-TenantId: 1

###  Unsubscribe tenant
DELETE http://localhost:8080/callback/tenant/tenant_1
X-TenantId: tenant_1